name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Extract lowercase owner, repo, and version
        id: vars
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
          OWNER_NAME=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')

          echo "REPO=$REPO_NAME" >> $GITHUB_ENV
          echo "OWNER=$OWNER_NAME" >> $GITHUB_ENV

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$OWNER/$REPO:latest .
      
      - name: Push Docker images
        run: |
          docker push ghcr.io/$OWNER/$REPO:latest

